### PR TITLE
fix/2824 adds missing emoji codes

### LINKED ISSUE #2824: Missing emoji codes
When I added emoji codes I somehow missed a bunch of important ones. Let's fix that!

### PR DESCRIPTION
**Pull request by holmesworcester**
Fixes https://github.com/TryQuiet/quiet/issues/2824

### Pull Request Checklist

- [x] I have linked this PR to a related GitHub issue.
- [x] I have added a description of the change (and Github issue number, if any) to the root [CHANGELOG.md](https://github.com/TryQuiet/quiet/blob/develop/CHANGELOG.md).

### (Optional) Mobile checklist

Please ensure you completed the following checks if you did any changes to the mobile package:

- [ ] I have run e2e tests for mobile
- [ ] I have updated base screenshots for visual regression tests

### CODE REVIEW

File: packages/desktop/src/renderer/components/widgets/channels/ChannelInput/utils/emojiCodes.ts [hunk 1]
```diff
@@ -671,6 +896,19 @@ const emoticons: EmojiMapping = {
   ":'-(": '😢',
   ":'D": '😂',
   ":'-)": '😂',
+  ':3': '😊',
+  ':-3': '😊',
+  XD: '😆',
```
Comment (adrastaea) [inline packages/desktop/src/renderer/components/widgets/channels/ChannelInput/utils/emojiCodes.ts]:
```suggestion
  'XD': '😆',
```
Is there a reason this wasn't wrapped in quotes?

File: packages/desktop/src/renderer/components/widgets/channels/ChannelInput/utils/emojiCodes.ts [hunk 2]
```diff
@@ -671,6 +896,19 @@ const emoticons: EmojiMapping = {
...
+  'X-D': '😆',
+  xD: '😆',
```
Comment (adrastaea) [inline packages/desktop/src/renderer/components/widgets/channels/ChannelInput/utils/emojiCodes.ts]:
```suggestion
  'xD': '😆',
```

**Review by islathehut — APPROVED** [review]
