### PR TITLE
Fix/mac autoupdater

### LINKED ISSUE #2965: Autoupdater is broken on mac

### PR DESCRIPTION
**Pull request by adrastaea**
Fixes an issue where triggering an update would stall out on Mac (and maybe others) because of the preventDefault guards that let us intercept default behavior and do cleanup or minimize instead of close in the case of macOS. 

* Adds an `updating` flag which is set before `app.quitAndInstall()` and lets other events be more permissive of default close behaviors when installing an update.

### Pull Request Checklist

- [x] I have linked this PR to a related GitHub issue.
- [x] I have added a description of the change (and Github issue number, if any) to the root [CHANGELOG.md](https://github.com/TryQuiet/quiet/blob/develop/CHANGELOG.md).

### (Optional) Mobile checklist

Please ensure you completed the following checks if you did any changes to the mobile package:

- [ ] I have run e2e tests for mobile
- [ ] I have updated base screenshots for visual regression tests

### CODE REVIEW

File: packages/desktop/src/main/main.ts [hunk 1]
```diff
@@ -560,6 +574,7 @@ app.on('ready', async () => {
 
   ipcMain.on('proceed-update', () => {
     logger.info('ipcMain: proceed-update')
+    updating = true
```
Comment (islathehut) [inline packages/desktop/src/main/main.ts:577]: Do we need to reset this to false anywhere?

Comment (adrastaea) [reply packages/desktop/src/main/main.ts:577]: I don't think so because the application should fully close and reinitialize. I can't actually test this without pushing out a new alpha though.
