### PR TITLE
Fix/non-admin-invite-links

### LINKED ISSUE #2727: Java script error for joining users on desktop
**Version**: 4.0.0
**System**: all desktop

**Issue**: The first user to join the community (not the owner, but the first user who joins from the owner's link) gets a JS error after a few minutes. Before getting the error, everything worked as expected. 

Below you can find print screen of the error and logs.

[Untitled document (1).txt](https://github.com/user-attachments/files/18675485/Untitled.document.1.txt)

Image

Note: once this issue is resolved Kinga should check if leaving community works.

### LINKED ISSUE #2729: Disable creating invites/QR codes in UI for non-admins
In localfirst auth only admins have the ability to generate invite codes and we've decided that we'll limit the functionality to admins (which currently means only the owner).

### PR DESCRIPTION
**Pull request by adrastaea**
Handles errors in the backend for non-admins trying to work with invite links. Adds UI for non-admins trying to add members

### Pull Request Checklist

- [x] I have linked this PR to a related GitHub issue.
- [x] I have added a description of the change (and Github issue number, if any) to the root [CHANGELOG.md](https://github.com/TryQuiet/quiet/blob/develop/CHANGELOG.md).

### (Optional) Mobile checklist

Please ensure you completed the following checks if you did any changes to the mobile package:

- [ ] I have run e2e tests for mobile
- [ ] I have updated base screenshots for visual regression tests

### CODE REVIEW

File: packages/desktop/src/renderer/components/Settings/Tabs/QRCode/QRCode.tsx [hunk 1]
```diff
@@ -1,10 +1,16 @@
...
 import { useDispatch, useSelector } from 'react-redux'
 
+import { styled } from '@mui/material/styles'
+import Typography from '@mui/material/Typography'
+
 import { Site } from '@quiet/common'
 import { connection } from '@quiet/state-manager'
 
 import { QRCodeComponent } from './QRCode.component'
+import { createLogger } from 'packages/desktop/src/renderer/logger'
```
Comment (islathehut) [inline packages/desktop/src/renderer/components/Settings/Tabs/QRCode/QRCode.tsx]: Make this a relative import

**Review by islathehut — CHANGES_REQUESTED** [review]

**Review by islathehut — APPROVED** [review]
